apiVersion: v1
kind: ConfigMap
metadata:
  name: smarter-device-manager
  namespace: 3dprint
data:
  conf.yaml: |
    - devicematch: ^ttyUSB[0-9]*$
      nummaxdevices: 1
    - devicematch: ^ttyACM[0-9]*$
      nummaxdevices: 1
    - devicematch: ^ttyS[0-9]*$
      nummaxdevices: 1
    - devicematch: ^video[0-9]*$
      nummaxdevices: 20
    - devicematch: "^v4l/by-id/usb-\\w+-video-\\w+$"
      nummaxdevices: 20
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: smarter-device-manager
  namespace: 3dprint
  labels:
    name: smarter-device-manager
    role: agent
spec:
  selector:
    matchLabels:
      name: smarter-device-manager
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels: 
        name: smarter-device-manager
      annotations:
        node.kubernetes.io/bootstrap-checkpoint: "true"
    spec: 
      nodeSelector:
        smarter-device-manager : enabled
      priorityClassName: "system-node-critical"
      hostname: smarter-device-management
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: smarter-device-manager
        image: registry.gitlab.com/arm-research/smarter/smarter-device-manager:v1.20.8
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        resources:
          limits:
            cpu: 100m
            memory: 15Mi
          requests:
            cpu: 10m
            memory: 15Mi
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
          - name: dev-dir
            mountPath: /dev
          - name: sys-dir
            mountPath: /sys
          - name: config
            mountPath: /root/config
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: dev-dir
          hostPath:
            path: /dev
        - name: sys-dir
          hostPath:
            path: /sys
        - name: config
          configMap:
             name: smarter-device-manager
      terminationGracePeriodSeconds: 30

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: octoprint-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: "octoprint.dupa.lol"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: octoprint
            port: 
              name: web
  - host: "debian.fritz.box"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: octoprint
            port: 
              name: web

---

apiVersion: v1
kind: Service
metadata:
  name: octoprint
  labels:
    app: octoprint
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: octoprint
---    
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: octoprint
  labels:
    app: octoprint
spec:
  serviceName: octoprint
  replicas: 1
  selector:
    matchLabels:
      app: octoprint
  template:
    metadata:
      labels:
        app: octoprint
    spec:
      containers:
      - name: octoprint
        image: octoprint/octoprint:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /octoprint
          name: octoprint-vol
        env:
        - name: ENABLE_MJPG_STREAMER
          value: "true"
        - name: MJPG_STREAMER_INPUT
          value: "-f 30 -r 1280x720"
        - name: CAMERA_DEV
          value: /dev/v4l/by-id/usb-046d_0821_06A45CC0-video-index0
        resources:
          limits:
            smarter-devices/ttyUSB0: 1
            smarter-devices/v4l_by-id_usb-046d_0821_06A45CC0-video-index0: 1
            smarter-devices/v4l_by-id_usb-046d_0821_06A45CC0-video-index1: 1
  volumeClaimTemplates:
  - metadata:
      name: octoprint-vol
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi